package com.ssic.cookbook.manager.dto;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

public class CategoryClassDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.independent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String independentFixingsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.big_category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String bigCategoryId;
    
    @Getter
    @Setter
    private String bigCategoryIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.cost
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Long cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_category_class.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.id
     *
     * @return the value of t_cb_category_class.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.id
     *
     * @param id the value for t_cb_category_class.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.independent_fixings_id
     *
     * @return the value of t_cb_category_class.independent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getIndependentFixingsId() {
        return independentFixingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.independent_fixings_id
     *
     * @param independentFixingsId the value for t_cb_category_class.independent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setIndependentFixingsId(String independentFixingsId) {
        this.independentFixingsId = independentFixingsId == null ? null : independentFixingsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.big_category_id
     *
     * @return the value of t_cb_category_class.big_category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getBigCategoryId() {
        return bigCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.big_category_id
     *
     * @param bigCategoryId the value for t_cb_category_class.big_category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setBigCategoryId(String bigCategoryId) {
        this.bigCategoryId = bigCategoryId == null ? null : bigCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.cost
     *
     * @return the value of t_cb_category_class.cost
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Long getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.cost
     *
     * @param cost the value for t_cb_category_class.cost
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCost(Long cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.create_time
     *
     * @return the value of t_cb_category_class.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.create_time
     *
     * @param createTime the value for t_cb_category_class.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.last_update_time
     *
     * @return the value of t_cb_category_class.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_category_class.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_category_class.stat
     *
     * @return the value of t_cb_category_class.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_category_class.stat
     *
     * @param stat the value for t_cb_category_class.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}