package com.ssic.cookbook.manager.dto;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

public class FixingsResultTypeDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.fixings_result_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private String fixingsResultId;

    @Getter
    @Setter
    private Date fixingsTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.product_category_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private String productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.create_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.last_update_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private Date lastUpdateTime;

    @Getter
    @Setter
    private Integer mealType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result_type.stat
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.id
     *
     * @return the value of t_cb_fixings_result_type.id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.id
     *
     * @param id the value for t_cb_fixings_result_type.id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.fixings_result_id
     *
     * @return the value of t_cb_fixings_result_type.fixings_result_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public String getFixingsResultId() {
        return fixingsResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.fixings_result_id
     *
     * @param fixingsResultId the value for t_cb_fixings_result_type.fixings_result_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setFixingsResultId(String fixingsResultId) {
        this.fixingsResultId = fixingsResultId == null ? null : fixingsResultId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.product_category_id
     *
     * @return the value of t_cb_fixings_result_type.product_category_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public String getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.product_category_id
     *
     * @param productCategoryId the value for t_cb_fixings_result_type.product_category_id
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setProductCategoryId(String productCategoryId) {
        this.productCategoryId = productCategoryId == null ? null : productCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.create_time
     *
     * @return the value of t_cb_fixings_result_type.create_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.create_time
     *
     * @param createTime the value for t_cb_fixings_result_type.create_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.last_update_time
     *
     * @return the value of t_cb_fixings_result_type.last_update_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_fixings_result_type.last_update_time
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result_type.stat
     *
     * @return the value of t_cb_fixings_result_type.stat
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result_type.stat
     *
     * @param stat the value for t_cb_fixings_result_type.stat
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}