package com.ssic.cookbook.manager.dto;


import java.io.Serializable;
import java.util.Date;

import com.ssic.base.redis.RedisKeyPrefix;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
//@RedisKeyPrefix(prefixValue="cookbook.manager.dto.ProductionMethodDtoList")
public class ProductionMethodDto implements Serializable  {
    
     /**   
     * serialVersionUID: （一句话描述这个变量表示什么）      
     */   
    
    private static final long serialVersionUID = 1412822229558830542L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String id;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.img_url
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.production_name
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String productionName;
    
    @Getter
    @Setter
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String productionMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_production_method.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Integer stat;
    @Getter
    @Setter
    private Integer star;
    @Getter
    @Setter
    private Integer end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.id
     *
     * @return the value of t_cb_production_method.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.id
     *
     * @param id the value for t_cb_production_method.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.img_url
     *
     * @return the value of t_cb_production_method.img_url
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.img_url
     *
     * @param imgUrl the value for t_cb_production_method.img_url
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.production_name
     *
     * @return the value of t_cb_production_method.production_name
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getProductionName() {
        return productionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.production_name
     *
     * @param productionName the value for t_cb_production_method.production_name
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setProductionName(String productionName) {
        this.productionName = productionName == null ? null : productionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.production_method
     *
     * @return the value of t_cb_production_method.production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getProductionMethod() {
        return productionMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.production_method
     *
     * @param productionMethod the value for t_cb_production_method.production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setProductionMethod(String productionMethod) {
        this.productionMethod = productionMethod == null ? null : productionMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.create_time
     *
     * @return the value of t_cb_production_method.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.create_time
     *
     * @param createTime the value for t_cb_production_method.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.last_update_time
     *
     * @return the value of t_cb_production_method.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_production_method.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_production_method.stat
     *
     * @return the value of t_cb_production_method.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_production_method.stat
     *
     * @param stat the value for t_cb_production_method.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}

