package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class FixingsResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.fixings_id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private String fixingsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.fixings_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private Integer fixingsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.create_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.last_update_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_fixings_result.stat
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.id
     *
     * @return the value of t_cb_fixings_result.id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.id
     *
     * @param id the value for t_cb_fixings_result.id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.fixings_id
     *
     * @return the value of t_cb_fixings_result.fixings_id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public String getFixingsId() {
        return fixingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.fixings_id
     *
     * @param fixingsId the value for t_cb_fixings_result.fixings_id
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setFixingsId(String fixingsId) {
        this.fixingsId = fixingsId == null ? null : fixingsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.fixings_type
     *
     * @return the value of t_cb_fixings_result.fixings_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Integer getFixingsType() {
        return fixingsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.fixings_type
     *
     * @param fixingsType the value for t_cb_fixings_result.fixings_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setFixingsType(Integer fixingsType) {
        this.fixingsType = fixingsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.create_time
     *
     * @return the value of t_cb_fixings_result.create_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.create_time
     *
     * @param createTime the value for t_cb_fixings_result.create_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.last_update_time
     *
     * @return the value of t_cb_fixings_result.last_update_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_fixings_result.last_update_time
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_fixings_result.stat
     *
     * @return the value of t_cb_fixings_result.stat
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_fixings_result.stat
     *
     * @param stat the value for t_cb_fixings_result.stat
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}