package com.ssic.cookbook.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FixingsResultTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public FixingsResultTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdIsNull() {
            addCriterion("fixings_result_id is null");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdIsNotNull() {
            addCriterion("fixings_result_id is not null");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdEqualTo(String value) {
            addCriterion("fixings_result_id =", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdNotEqualTo(String value) {
            addCriterion("fixings_result_id <>", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdGreaterThan(String value) {
            addCriterion("fixings_result_id >", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdGreaterThanOrEqualTo(String value) {
            addCriterion("fixings_result_id >=", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdLessThan(String value) {
            addCriterion("fixings_result_id <", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdLessThanOrEqualTo(String value) {
            addCriterion("fixings_result_id <=", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdLike(String value) {
            addCriterion("fixings_result_id like", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdNotLike(String value) {
            addCriterion("fixings_result_id not like", value, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdIn(List<String> values) {
            addCriterion("fixings_result_id in", values, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdNotIn(List<String> values) {
            addCriterion("fixings_result_id not in", values, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdBetween(String value1, String value2) {
            addCriterion("fixings_result_id between", value1, value2, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andFixingsResultIdNotBetween(String value1, String value2) {
            addCriterion("fixings_result_id not between", value1, value2, "fixingsResultId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNull() {
            addCriterion("product_category_id is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNotNull() {
            addCriterion("product_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdEqualTo(String value) {
            addCriterion("product_category_id =", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotEqualTo(String value) {
            addCriterion("product_category_id <>", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThan(String value) {
            addCriterion("product_category_id >", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_category_id >=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThan(String value) {
            addCriterion("product_category_id <", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("product_category_id <=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLike(String value) {
            addCriterion("product_category_id like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotLike(String value) {
            addCriterion("product_category_id not like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIn(List<String> values) {
            addCriterion("product_category_id in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotIn(List<String> values) {
            addCriterion("product_category_id not in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdBetween(String value1, String value2) {
            addCriterion("product_category_id between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotBetween(String value1, String value2) {
            addCriterion("product_category_id not between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andMealTypeIsNull() {
            addCriterion("meal_type is null");
            return (Criteria) this;
        }

        public Criteria andMealTypeIsNotNull() {
            addCriterion("meal_type is not null");
            return (Criteria) this;
        }

        public Criteria andMealTypeEqualTo(Integer value) {
            addCriterion("meal_type =", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeNotEqualTo(Integer value) {
            addCriterion("meal_type <>", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeGreaterThan(Integer value) {
            addCriterion("meal_type >", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("meal_type >=", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeLessThan(Integer value) {
            addCriterion("meal_type <", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeLessThanOrEqualTo(Integer value) {
            addCriterion("meal_type <=", value, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeIn(List<Integer> values) {
            addCriterion("meal_type in", values, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeNotIn(List<Integer> values) {
            addCriterion("meal_type not in", values, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeBetween(Integer value1, Integer value2) {
            addCriterion("meal_type between", value1, value2, "mealType");
            return (Criteria) this;
        }

        public Criteria andMealTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("meal_type not between", value1, value2, "mealType");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeIsNull() {
            addCriterion("fixings_time is null");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeIsNotNull() {
            addCriterion("fixings_time is not null");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeEqualTo(Date value) {
            addCriterion("fixings_time =", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeNotEqualTo(Date value) {
            addCriterion("fixings_time <>", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeGreaterThan(Date value) {
            addCriterion("fixings_time >", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fixings_time >=", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeLessThan(Date value) {
            addCriterion("fixings_time <", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeLessThanOrEqualTo(Date value) {
            addCriterion("fixings_time <=", value, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeIn(List<Date> values) {
            addCriterion("fixings_time in", values, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeNotIn(List<Date> values) {
            addCriterion("fixings_time not in", values, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeBetween(Date value1, Date value2) {
            addCriterion("fixings_time between", value1, value2, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andFixingsTimeNotBetween(Date value1, Date value2) {
            addCriterion("fixings_time not between", value1, value2, "fixingsTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 04 14:25:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}