package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class IntelligentFixingsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.category_count
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Long categoryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.intelligent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private String intelligentFixingsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_category.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.id
     *
     * @return the value of t_cb_intelligent_fixings_category.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.id
     *
     * @param id the value for t_cb_intelligent_fixings_category.id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.category_id
     *
     * @return the value of t_cb_intelligent_fixings_category.category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.category_id
     *
     * @param categoryId the value for t_cb_intelligent_fixings_category.category_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.category_count
     *
     * @return the value of t_cb_intelligent_fixings_category.category_count
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Long getCategoryCount() {
        return categoryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.category_count
     *
     * @param categoryCount the value for t_cb_intelligent_fixings_category.category_count
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCategoryCount(Long categoryCount) {
        this.categoryCount = categoryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.intelligent_fixings_id
     *
     * @return the value of t_cb_intelligent_fixings_category.intelligent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public String getIntelligentFixingsId() {
        return intelligentFixingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.intelligent_fixings_id
     *
     * @param intelligentFixingsId the value for t_cb_intelligent_fixings_category.intelligent_fixings_id
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setIntelligentFixingsId(String intelligentFixingsId) {
        this.intelligentFixingsId = intelligentFixingsId == null ? null : intelligentFixingsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.create_time
     *
     * @return the value of t_cb_intelligent_fixings_category.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.create_time
     *
     * @param createTime the value for t_cb_intelligent_fixings_category.create_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.last_update_time
     *
     * @return the value of t_cb_intelligent_fixings_category.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_intelligent_fixings_category.last_update_time
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_category.stat
     *
     * @return the value of t_cb_intelligent_fixings_category.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_category.stat
     *
     * @param stat the value for t_cb_intelligent_fixings_category.stat
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}