package com.ssic.cookbook.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IntelligentFixingsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public IntelligentFixingsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSetMealNameIsNull() {
            addCriterion("set_meal_name is null");
            return (Criteria) this;
        }

        public Criteria andSetMealNameIsNotNull() {
            addCriterion("set_meal_name is not null");
            return (Criteria) this;
        }

        public Criteria andSetMealNameEqualTo(String value) {
            addCriterion("set_meal_name =", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameNotEqualTo(String value) {
            addCriterion("set_meal_name <>", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameGreaterThan(String value) {
            addCriterion("set_meal_name >", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameGreaterThanOrEqualTo(String value) {
            addCriterion("set_meal_name >=", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameLessThan(String value) {
            addCriterion("set_meal_name <", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameLessThanOrEqualTo(String value) {
            addCriterion("set_meal_name <=", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameLike(String value) {
            addCriterion("set_meal_name like", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameNotLike(String value) {
            addCriterion("set_meal_name not like", value, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameIn(List<String> values) {
            addCriterion("set_meal_name in", values, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameNotIn(List<String> values) {
            addCriterion("set_meal_name not in", values, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameBetween(String value1, String value2) {
            addCriterion("set_meal_name between", value1, value2, "setMealName");
            return (Criteria) this;
        }

        public Criteria andSetMealNameNotBetween(String value1, String value2) {
            addCriterion("set_meal_name not between", value1, value2, "setMealName");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdIsNull() {
            addCriterion("fixings_master_id is null");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdIsNotNull() {
            addCriterion("fixings_master_id is not null");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdEqualTo(String value) {
            addCriterion("fixings_master_id =", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdNotEqualTo(String value) {
            addCriterion("fixings_master_id <>", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdGreaterThan(String value) {
            addCriterion("fixings_master_id >", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdGreaterThanOrEqualTo(String value) {
            addCriterion("fixings_master_id >=", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdLessThan(String value) {
            addCriterion("fixings_master_id <", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdLessThanOrEqualTo(String value) {
            addCriterion("fixings_master_id <=", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdLike(String value) {
            addCriterion("fixings_master_id like", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdNotLike(String value) {
            addCriterion("fixings_master_id not like", value, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdIn(List<String> values) {
            addCriterion("fixings_master_id in", values, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdNotIn(List<String> values) {
            addCriterion("fixings_master_id not in", values, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdBetween(String value1, String value2) {
            addCriterion("fixings_master_id between", value1, value2, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andFixingsMasterIdNotBetween(String value1, String value2) {
            addCriterion("fixings_master_id not between", value1, value2, "fixingsMasterId");
            return (Criteria) this;
        }

        public Criteria andLunchCountIsNull() {
            addCriterion("lunch_count is null");
            return (Criteria) this;
        }

        public Criteria andLunchCountIsNotNull() {
            addCriterion("lunch_count is not null");
            return (Criteria) this;
        }

        public Criteria andLunchCountEqualTo(Integer value) {
            addCriterion("lunch_count =", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountNotEqualTo(Integer value) {
            addCriterion("lunch_count <>", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountGreaterThan(Integer value) {
            addCriterion("lunch_count >", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("lunch_count >=", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountLessThan(Integer value) {
            addCriterion("lunch_count <", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountLessThanOrEqualTo(Integer value) {
            addCriterion("lunch_count <=", value, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountIn(List<Integer> values) {
            addCriterion("lunch_count in", values, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountNotIn(List<Integer> values) {
            addCriterion("lunch_count not in", values, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountBetween(Integer value1, Integer value2) {
            addCriterion("lunch_count between", value1, value2, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andLunchCountNotBetween(Integer value1, Integer value2) {
            addCriterion("lunch_count not between", value1, value2, "lunchCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountIsNull() {
            addCriterion("dinner_count is null");
            return (Criteria) this;
        }

        public Criteria andDinnerCountIsNotNull() {
            addCriterion("dinner_count is not null");
            return (Criteria) this;
        }

        public Criteria andDinnerCountEqualTo(Integer value) {
            addCriterion("dinner_count =", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountNotEqualTo(Integer value) {
            addCriterion("dinner_count <>", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountGreaterThan(Integer value) {
            addCriterion("dinner_count >", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("dinner_count >=", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountLessThan(Integer value) {
            addCriterion("dinner_count <", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountLessThanOrEqualTo(Integer value) {
            addCriterion("dinner_count <=", value, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountIn(List<Integer> values) {
            addCriterion("dinner_count in", values, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountNotIn(List<Integer> values) {
            addCriterion("dinner_count not in", values, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountBetween(Integer value1, Integer value2) {
            addCriterion("dinner_count between", value1, value2, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andDinnerCountNotBetween(Integer value1, Integer value2) {
            addCriterion("dinner_count not between", value1, value2, "dinnerCount");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIsNull() {
            addCriterion("product_taste_id is null");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIsNotNull() {
            addCriterion("product_taste_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdEqualTo(String value) {
            addCriterion("product_taste_id =", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotEqualTo(String value) {
            addCriterion("product_taste_id <>", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdGreaterThan(String value) {
            addCriterion("product_taste_id >", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_taste_id >=", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLessThan(String value) {
            addCriterion("product_taste_id <", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLessThanOrEqualTo(String value) {
            addCriterion("product_taste_id <=", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLike(String value) {
            addCriterion("product_taste_id like", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotLike(String value) {
            addCriterion("product_taste_id not like", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIn(List<String> values) {
            addCriterion("product_taste_id in", values, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotIn(List<String> values) {
            addCriterion("product_taste_id not in", values, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdBetween(String value1, String value2) {
            addCriterion("product_taste_id between", value1, value2, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotBetween(String value1, String value2) {
            addCriterion("product_taste_id not between", value1, value2, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIsNull() {
            addCriterion("product_color_id is null");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIsNotNull() {
            addCriterion("product_color_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorIdEqualTo(String value) {
            addCriterion("product_color_id =", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotEqualTo(String value) {
            addCriterion("product_color_id <>", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdGreaterThan(String value) {
            addCriterion("product_color_id >", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_color_id >=", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLessThan(String value) {
            addCriterion("product_color_id <", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLessThanOrEqualTo(String value) {
            addCriterion("product_color_id <=", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLike(String value) {
            addCriterion("product_color_id like", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotLike(String value) {
            addCriterion("product_color_id not like", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIn(List<String> values) {
            addCriterion("product_color_id in", values, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotIn(List<String> values) {
            addCriterion("product_color_id not in", values, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdBetween(String value1, String value2) {
            addCriterion("product_color_id between", value1, value2, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotBetween(String value1, String value2) {
            addCriterion("product_color_id not between", value1, value2, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIsNull() {
            addCriterion("product_cuisine_id is null");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIsNotNull() {
            addCriterion("product_cuisine_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdEqualTo(String value) {
            addCriterion("product_cuisine_id =", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotEqualTo(String value) {
            addCriterion("product_cuisine_id <>", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdGreaterThan(String value) {
            addCriterion("product_cuisine_id >", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_cuisine_id >=", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLessThan(String value) {
            addCriterion("product_cuisine_id <", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLessThanOrEqualTo(String value) {
            addCriterion("product_cuisine_id <=", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLike(String value) {
            addCriterion("product_cuisine_id like", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotLike(String value) {
            addCriterion("product_cuisine_id not like", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIn(List<String> values) {
            addCriterion("product_cuisine_id in", values, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotIn(List<String> values) {
            addCriterion("product_cuisine_id not in", values, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdBetween(String value1, String value2) {
            addCriterion("product_cuisine_id between", value1, value2, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotBetween(String value1, String value2) {
            addCriterion("product_cuisine_id not between", value1, value2, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIsNull() {
            addCriterion("product_style_id is null");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIsNotNull() {
            addCriterion("product_style_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdEqualTo(String value) {
            addCriterion("product_style_id =", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotEqualTo(String value) {
            addCriterion("product_style_id <>", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdGreaterThan(String value) {
            addCriterion("product_style_id >", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_style_id >=", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLessThan(String value) {
            addCriterion("product_style_id <", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLessThanOrEqualTo(String value) {
            addCriterion("product_style_id <=", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLike(String value) {
            addCriterion("product_style_id like", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotLike(String value) {
            addCriterion("product_style_id not like", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIn(List<String> values) {
            addCriterion("product_style_id in", values, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotIn(List<String> values) {
            addCriterion("product_style_id not in", values, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdBetween(String value1, String value2) {
            addCriterion("product_style_id between", value1, value2, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotBetween(String value1, String value2) {
            addCriterion("product_style_id not between", value1, value2, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIsNull() {
            addCriterion("product_shape_id is null");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIsNotNull() {
            addCriterion("product_shape_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdEqualTo(String value) {
            addCriterion("product_shape_id =", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotEqualTo(String value) {
            addCriterion("product_shape_id <>", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdGreaterThan(String value) {
            addCriterion("product_shape_id >", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_shape_id >=", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLessThan(String value) {
            addCriterion("product_shape_id <", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLessThanOrEqualTo(String value) {
            addCriterion("product_shape_id <=", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLike(String value) {
            addCriterion("product_shape_id like", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotLike(String value) {
            addCriterion("product_shape_id not like", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIn(List<String> values) {
            addCriterion("product_shape_id in", values, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotIn(List<String> values) {
            addCriterion("product_shape_id not in", values, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdBetween(String value1, String value2) {
            addCriterion("product_shape_id between", value1, value2, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotBetween(String value1, String value2) {
            addCriterion("product_shape_id not between", value1, value2, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorIsNull() {
            addCriterion("total_cost_operator is null");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorIsNotNull() {
            addCriterion("total_cost_operator is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorEqualTo(String value) {
            addCriterion("total_cost_operator =", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorNotEqualTo(String value) {
            addCriterion("total_cost_operator <>", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorGreaterThan(String value) {
            addCriterion("total_cost_operator >", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("total_cost_operator >=", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorLessThan(String value) {
            addCriterion("total_cost_operator <", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorLessThanOrEqualTo(String value) {
            addCriterion("total_cost_operator <=", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorLike(String value) {
            addCriterion("total_cost_operator like", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorNotLike(String value) {
            addCriterion("total_cost_operator not like", value, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorIn(List<String> values) {
            addCriterion("total_cost_operator in", values, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorNotIn(List<String> values) {
            addCriterion("total_cost_operator not in", values, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorBetween(String value1, String value2) {
            addCriterion("total_cost_operator between", value1, value2, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostOperatorNotBetween(String value1, String value2) {
            addCriterion("total_cost_operator not between", value1, value2, "totalCostOperator");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNull() {
            addCriterion("total_cost is null");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNotNull() {
            addCriterion("total_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCostEqualTo(Long value) {
            addCriterion("total_cost =", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotEqualTo(Long value) {
            addCriterion("total_cost <>", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThan(Long value) {
            addCriterion("total_cost >", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThanOrEqualTo(Long value) {
            addCriterion("total_cost >=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThan(Long value) {
            addCriterion("total_cost <", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThanOrEqualTo(Long value) {
            addCriterion("total_cost <=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostIn(List<Long> values) {
            addCriterion("total_cost in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotIn(List<Long> values) {
            addCriterion("total_cost not in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostBetween(Long value1, Long value2) {
            addCriterion("total_cost between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotBetween(Long value1, Long value2) {
            addCriterion("total_cost not between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorIsNull() {
            addCriterion("total_fixed_price_operator is null");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorIsNotNull() {
            addCriterion("total_fixed_price_operator is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorEqualTo(String value) {
            addCriterion("total_fixed_price_operator =", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorNotEqualTo(String value) {
            addCriterion("total_fixed_price_operator <>", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorGreaterThan(String value) {
            addCriterion("total_fixed_price_operator >", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("total_fixed_price_operator >=", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorLessThan(String value) {
            addCriterion("total_fixed_price_operator <", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorLessThanOrEqualTo(String value) {
            addCriterion("total_fixed_price_operator <=", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorLike(String value) {
            addCriterion("total_fixed_price_operator like", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorNotLike(String value) {
            addCriterion("total_fixed_price_operator not like", value, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorIn(List<String> values) {
            addCriterion("total_fixed_price_operator in", values, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorNotIn(List<String> values) {
            addCriterion("total_fixed_price_operator not in", values, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorBetween(String value1, String value2) {
            addCriterion("total_fixed_price_operator between", value1, value2, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceOperatorNotBetween(String value1, String value2) {
            addCriterion("total_fixed_price_operator not between", value1, value2, "totalFixedPriceOperator");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceIsNull() {
            addCriterion("total_fixed_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceIsNotNull() {
            addCriterion("total_fixed_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceEqualTo(Long value) {
            addCriterion("total_fixed_price =", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceNotEqualTo(Long value) {
            addCriterion("total_fixed_price <>", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceGreaterThan(Long value) {
            addCriterion("total_fixed_price >", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("total_fixed_price >=", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceLessThan(Long value) {
            addCriterion("total_fixed_price <", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceLessThanOrEqualTo(Long value) {
            addCriterion("total_fixed_price <=", value, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceIn(List<Long> values) {
            addCriterion("total_fixed_price in", values, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceNotIn(List<Long> values) {
            addCriterion("total_fixed_price not in", values, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceBetween(Long value1, Long value2) {
            addCriterion("total_fixed_price between", value1, value2, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andTotalFixedPriceNotBetween(Long value1, Long value2) {
            addCriterion("total_fixed_price not between", value1, value2, "totalFixedPrice");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsIsNull() {
            addCriterion("is_sensitive_ingredients is null");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsIsNotNull() {
            addCriterion("is_sensitive_ingredients is not null");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsEqualTo(Integer value) {
            addCriterion("is_sensitive_ingredients =", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsNotEqualTo(Integer value) {
            addCriterion("is_sensitive_ingredients <>", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsGreaterThan(Integer value) {
            addCriterion("is_sensitive_ingredients >", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_sensitive_ingredients >=", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsLessThan(Integer value) {
            addCriterion("is_sensitive_ingredients <", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsLessThanOrEqualTo(Integer value) {
            addCriterion("is_sensitive_ingredients <=", value, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsIn(List<Integer> values) {
            addCriterion("is_sensitive_ingredients in", values, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsNotIn(List<Integer> values) {
            addCriterion("is_sensitive_ingredients not in", values, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsBetween(Integer value1, Integer value2) {
            addCriterion("is_sensitive_ingredients between", value1, value2, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andIsSensitiveIngredientsNotBetween(Integer value1, Integer value2) {
            addCriterion("is_sensitive_ingredients not between", value1, value2, "isSensitiveIngredients");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeIsNull() {
            addCriterion("fixings_start_time is null");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeIsNotNull() {
            addCriterion("fixings_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeEqualTo(Date value) {
            addCriterion("fixings_start_time =", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeNotEqualTo(Date value) {
            addCriterion("fixings_start_time <>", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeGreaterThan(Date value) {
            addCriterion("fixings_start_time >", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fixings_start_time >=", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeLessThan(Date value) {
            addCriterion("fixings_start_time <", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("fixings_start_time <=", value, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeIn(List<Date> values) {
            addCriterion("fixings_start_time in", values, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeNotIn(List<Date> values) {
            addCriterion("fixings_start_time not in", values, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeBetween(Date value1, Date value2) {
            addCriterion("fixings_start_time between", value1, value2, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("fixings_start_time not between", value1, value2, "fixingsStartTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeIsNull() {
            addCriterion("fixings_end_time is null");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeIsNotNull() {
            addCriterion("fixings_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeEqualTo(Date value) {
            addCriterion("fixings_end_time =", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeNotEqualTo(Date value) {
            addCriterion("fixings_end_time <>", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeGreaterThan(Date value) {
            addCriterion("fixings_end_time >", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fixings_end_time >=", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeLessThan(Date value) {
            addCriterion("fixings_end_time <", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("fixings_end_time <=", value, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeIn(List<Date> values) {
            addCriterion("fixings_end_time in", values, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeNotIn(List<Date> values) {
            addCriterion("fixings_end_time not in", values, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeBetween(Date value1, Date value2) {
            addCriterion("fixings_end_time between", value1, value2, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andFixingsEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("fixings_end_time not between", value1, value2, "fixingsEndTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 17 16:30:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_intelligent_fixings
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}