package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class IntelligentFixingsTaste {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.taste_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String tasteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String intelligentFixingsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_taste.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.id
     *
     * @return the value of t_cb_intelligent_fixings_taste.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.id
     *
     * @param id the value for t_cb_intelligent_fixings_taste.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.taste_id
     *
     * @return the value of t_cb_intelligent_fixings_taste.taste_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getTasteId() {
        return tasteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.taste_id
     *
     * @param tasteId the value for t_cb_intelligent_fixings_taste.taste_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setTasteId(String tasteId) {
        this.tasteId = tasteId == null ? null : tasteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.intelligent_fixings_id
     *
     * @return the value of t_cb_intelligent_fixings_taste.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getIntelligentFixingsId() {
        return intelligentFixingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.intelligent_fixings_id
     *
     * @param intelligentFixingsId the value for t_cb_intelligent_fixings_taste.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setIntelligentFixingsId(String intelligentFixingsId) {
        this.intelligentFixingsId = intelligentFixingsId == null ? null : intelligentFixingsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.create_time
     *
     * @return the value of t_cb_intelligent_fixings_taste.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.create_time
     *
     * @param createTime the value for t_cb_intelligent_fixings_taste.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.last_update_time
     *
     * @return the value of t_cb_intelligent_fixings_taste.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_intelligent_fixings_taste.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_taste.stat
     *
     * @return the value of t_cb_intelligent_fixings_taste.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_taste.stat
     *
     * @param stat the value for t_cb_intelligent_fixings_taste.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}