package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class IntelligentFixingsCuisine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.cuisine_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String cuisineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private String intelligentFixingsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_intelligent_fixings_cuisine.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.id
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.id
     *
     * @param id the value for t_cb_intelligent_fixings_cuisine.id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.cuisine_id
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.cuisine_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getCuisineId() {
        return cuisineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.cuisine_id
     *
     * @param cuisineId the value for t_cb_intelligent_fixings_cuisine.cuisine_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setCuisineId(String cuisineId) {
        this.cuisineId = cuisineId == null ? null : cuisineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.intelligent_fixings_id
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public String getIntelligentFixingsId() {
        return intelligentFixingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.intelligent_fixings_id
     *
     * @param intelligentFixingsId the value for t_cb_intelligent_fixings_cuisine.intelligent_fixings_id
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setIntelligentFixingsId(String intelligentFixingsId) {
        this.intelligentFixingsId = intelligentFixingsId == null ? null : intelligentFixingsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.create_time
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.create_time
     *
     * @param createTime the value for t_cb_intelligent_fixings_cuisine.create_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.last_update_time
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_intelligent_fixings_cuisine.last_update_time
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_intelligent_fixings_cuisine.stat
     *
     * @return the value of t_cb_intelligent_fixings_cuisine.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_intelligent_fixings_cuisine.stat
     *
     * @param stat the value for t_cb_intelligent_fixings_cuisine.stat
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}