package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class MaterialNutrition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.nutrition_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private String nutritionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.create_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.last_update_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.stat
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_material_nutrition.material_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    private String materialId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.id
     *
     * @return the value of t_cb_material_nutrition.id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.id
     *
     * @param id the value for t_cb_material_nutrition.id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.nutrition_id
     *
     * @return the value of t_cb_material_nutrition.nutrition_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public String getNutritionId() {
        return nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.nutrition_id
     *
     * @param nutritionId the value for t_cb_material_nutrition.nutrition_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setNutritionId(String nutritionId) {
        this.nutritionId = nutritionId == null ? null : nutritionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.create_time
     *
     * @return the value of t_cb_material_nutrition.create_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.create_time
     *
     * @param createTime the value for t_cb_material_nutrition.create_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.last_update_time
     *
     * @return the value of t_cb_material_nutrition.last_update_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_material_nutrition.last_update_time
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.stat
     *
     * @return the value of t_cb_material_nutrition.stat
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.stat
     *
     * @param stat the value for t_cb_material_nutrition.stat
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_material_nutrition.material_id
     *
     * @return the value of t_cb_material_nutrition.material_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_material_nutrition.material_id
     *
     * @param materialId the value for t_cb_material_nutrition.material_id
     *
     * @mbggenerated Tue Dec 22 17:18:05 CST 2015
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId == null ? null : materialId.trim();
    }
}