package com.ssic.cookbook.manager.pojo;

import java.util.Date;

public class Nutrition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.name
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.content
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private Long content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.unit
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.create_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.last_update_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.stat
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.param_id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private String paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cb_nutrition.param_type
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    private String paramType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.id
     *
     * @return the value of t_cb_nutrition.id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.id
     *
     * @param id the value for t_cb_nutrition.id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.name
     *
     * @return the value of t_cb_nutrition.name
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.name
     *
     * @param name the value for t_cb_nutrition.name
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.content
     *
     * @return the value of t_cb_nutrition.content
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public Long getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.content
     *
     * @param content the value for t_cb_nutrition.content
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setContent(Long content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.unit
     *
     * @return the value of t_cb_nutrition.unit
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.unit
     *
     * @param unit the value for t_cb_nutrition.unit
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.create_time
     *
     * @return the value of t_cb_nutrition.create_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.create_time
     *
     * @param createTime the value for t_cb_nutrition.create_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.last_update_time
     *
     * @return the value of t_cb_nutrition.last_update_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.last_update_time
     *
     * @param lastUpdateTime the value for t_cb_nutrition.last_update_time
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.stat
     *
     * @return the value of t_cb_nutrition.stat
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.stat
     *
     * @param stat the value for t_cb_nutrition.stat
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.param_id
     *
     * @return the value of t_cb_nutrition.param_id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public String getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.param_id
     *
     * @param paramId the value for t_cb_nutrition.param_id
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setParamId(String paramId) {
        this.paramId = paramId == null ? null : paramId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cb_nutrition.param_type
     *
     * @return the value of t_cb_nutrition.param_type
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cb_nutrition.param_type
     *
     * @param paramType the value for t_cb_nutrition.param_type
     *
     * @mbggenerated Wed Jan 13 11:47:51 CST 2016
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }
}