package com.ssic.cookbook.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNull() {
            addCriterion("product_category_id is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNotNull() {
            addCriterion("product_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdEqualTo(String value) {
            addCriterion("product_category_id =", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotEqualTo(String value) {
            addCriterion("product_category_id <>", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThan(String value) {
            addCriterion("product_category_id >", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_category_id >=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThan(String value) {
            addCriterion("product_category_id <", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("product_category_id <=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLike(String value) {
            addCriterion("product_category_id like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotLike(String value) {
            addCriterion("product_category_id not like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIn(List<String> values) {
            addCriterion("product_category_id in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotIn(List<String> values) {
            addCriterion("product_category_id not in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdBetween(String value1, String value2) {
            addCriterion("product_category_id between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotBetween(String value1, String value2) {
            addCriterion("product_category_id not between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIsNull() {
            addCriterion("product_taste_id is null");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIsNotNull() {
            addCriterion("product_taste_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdEqualTo(String value) {
            addCriterion("product_taste_id =", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotEqualTo(String value) {
            addCriterion("product_taste_id <>", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdGreaterThan(String value) {
            addCriterion("product_taste_id >", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_taste_id >=", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLessThan(String value) {
            addCriterion("product_taste_id <", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLessThanOrEqualTo(String value) {
            addCriterion("product_taste_id <=", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdLike(String value) {
            addCriterion("product_taste_id like", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotLike(String value) {
            addCriterion("product_taste_id not like", value, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdIn(List<String> values) {
            addCriterion("product_taste_id in", values, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotIn(List<String> values) {
            addCriterion("product_taste_id not in", values, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdBetween(String value1, String value2) {
            addCriterion("product_taste_id between", value1, value2, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductTasteIdNotBetween(String value1, String value2) {
            addCriterion("product_taste_id not between", value1, value2, "productTasteId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIsNull() {
            addCriterion("product_color_id is null");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIsNotNull() {
            addCriterion("product_color_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorIdEqualTo(String value) {
            addCriterion("product_color_id =", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotEqualTo(String value) {
            addCriterion("product_color_id <>", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdGreaterThan(String value) {
            addCriterion("product_color_id >", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_color_id >=", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLessThan(String value) {
            addCriterion("product_color_id <", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLessThanOrEqualTo(String value) {
            addCriterion("product_color_id <=", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdLike(String value) {
            addCriterion("product_color_id like", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotLike(String value) {
            addCriterion("product_color_id not like", value, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdIn(List<String> values) {
            addCriterion("product_color_id in", values, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotIn(List<String> values) {
            addCriterion("product_color_id not in", values, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdBetween(String value1, String value2) {
            addCriterion("product_color_id between", value1, value2, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductColorIdNotBetween(String value1, String value2) {
            addCriterion("product_color_id not between", value1, value2, "productColorId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIsNull() {
            addCriterion("product_cuisine_id is null");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIsNotNull() {
            addCriterion("product_cuisine_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdEqualTo(String value) {
            addCriterion("product_cuisine_id =", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotEqualTo(String value) {
            addCriterion("product_cuisine_id <>", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdGreaterThan(String value) {
            addCriterion("product_cuisine_id >", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_cuisine_id >=", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLessThan(String value) {
            addCriterion("product_cuisine_id <", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLessThanOrEqualTo(String value) {
            addCriterion("product_cuisine_id <=", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdLike(String value) {
            addCriterion("product_cuisine_id like", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotLike(String value) {
            addCriterion("product_cuisine_id not like", value, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdIn(List<String> values) {
            addCriterion("product_cuisine_id in", values, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotIn(List<String> values) {
            addCriterion("product_cuisine_id not in", values, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdBetween(String value1, String value2) {
            addCriterion("product_cuisine_id between", value1, value2, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductCuisineIdNotBetween(String value1, String value2) {
            addCriterion("product_cuisine_id not between", value1, value2, "productCuisineId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIsNull() {
            addCriterion("product_style_id is null");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIsNotNull() {
            addCriterion("product_style_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdEqualTo(String value) {
            addCriterion("product_style_id =", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotEqualTo(String value) {
            addCriterion("product_style_id <>", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdGreaterThan(String value) {
            addCriterion("product_style_id >", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_style_id >=", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLessThan(String value) {
            addCriterion("product_style_id <", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLessThanOrEqualTo(String value) {
            addCriterion("product_style_id <=", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdLike(String value) {
            addCriterion("product_style_id like", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotLike(String value) {
            addCriterion("product_style_id not like", value, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdIn(List<String> values) {
            addCriterion("product_style_id in", values, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotIn(List<String> values) {
            addCriterion("product_style_id not in", values, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdBetween(String value1, String value2) {
            addCriterion("product_style_id between", value1, value2, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductStyleIdNotBetween(String value1, String value2) {
            addCriterion("product_style_id not between", value1, value2, "productStyleId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIsNull() {
            addCriterion("product_shape_id is null");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIsNotNull() {
            addCriterion("product_shape_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdEqualTo(String value) {
            addCriterion("product_shape_id =", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotEqualTo(String value) {
            addCriterion("product_shape_id <>", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdGreaterThan(String value) {
            addCriterion("product_shape_id >", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_shape_id >=", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLessThan(String value) {
            addCriterion("product_shape_id <", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLessThanOrEqualTo(String value) {
            addCriterion("product_shape_id <=", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdLike(String value) {
            addCriterion("product_shape_id like", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotLike(String value) {
            addCriterion("product_shape_id not like", value, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdIn(List<String> values) {
            addCriterion("product_shape_id in", values, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotIn(List<String> values) {
            addCriterion("product_shape_id not in", values, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdBetween(String value1, String value2) {
            addCriterion("product_shape_id between", value1, value2, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andProductShapeIdNotBetween(String value1, String value2) {
            addCriterion("product_shape_id not between", value1, value2, "productShapeId");
            return (Criteria) this;
        }

        public Criteria andSingleCostIsNull() {
            addCriterion("single_cost is null");
            return (Criteria) this;
        }

        public Criteria andSingleCostIsNotNull() {
            addCriterion("single_cost is not null");
            return (Criteria) this;
        }

        public Criteria andSingleCostEqualTo(Long value) {
            addCriterion("single_cost =", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostNotEqualTo(Long value) {
            addCriterion("single_cost <>", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostGreaterThan(Long value) {
            addCriterion("single_cost >", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostGreaterThanOrEqualTo(Long value) {
            addCriterion("single_cost >=", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostLessThan(Long value) {
            addCriterion("single_cost <", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostLessThanOrEqualTo(Long value) {
            addCriterion("single_cost <=", value, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostIn(List<Long> values) {
            addCriterion("single_cost in", values, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostNotIn(List<Long> values) {
            addCriterion("single_cost not in", values, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostBetween(Long value1, Long value2) {
            addCriterion("single_cost between", value1, value2, "singleCost");
            return (Criteria) this;
        }

        public Criteria andSingleCostNotBetween(Long value1, Long value2) {
            addCriterion("single_cost not between", value1, value2, "singleCost");
            return (Criteria) this;
        }

        public Criteria andEachPricingIsNull() {
            addCriterion("each_pricing is null");
            return (Criteria) this;
        }

        public Criteria andEachPricingIsNotNull() {
            addCriterion("each_pricing is not null");
            return (Criteria) this;
        }

        public Criteria andEachPricingEqualTo(Long value) {
            addCriterion("each_pricing =", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingNotEqualTo(Long value) {
            addCriterion("each_pricing <>", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingGreaterThan(Long value) {
            addCriterion("each_pricing >", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingGreaterThanOrEqualTo(Long value) {
            addCriterion("each_pricing >=", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingLessThan(Long value) {
            addCriterion("each_pricing <", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingLessThanOrEqualTo(Long value) {
            addCriterion("each_pricing <=", value, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingIn(List<Long> values) {
            addCriterion("each_pricing in", values, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingNotIn(List<Long> values) {
            addCriterion("each_pricing not in", values, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingBetween(Long value1, Long value2) {
            addCriterion("each_pricing between", value1, value2, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andEachPricingNotBetween(Long value1, Long value2) {
            addCriterion("each_pricing not between", value1, value2, "eachPricing");
            return (Criteria) this;
        }

        public Criteria andSingleWeightIsNull() {
            addCriterion("single_weight is null");
            return (Criteria) this;
        }

        public Criteria andSingleWeightIsNotNull() {
            addCriterion("single_weight is not null");
            return (Criteria) this;
        }

        public Criteria andSingleWeightEqualTo(Integer value) {
            addCriterion("single_weight =", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightNotEqualTo(Integer value) {
            addCriterion("single_weight <>", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightGreaterThan(Integer value) {
            addCriterion("single_weight >", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("single_weight >=", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightLessThan(Integer value) {
            addCriterion("single_weight <", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightLessThanOrEqualTo(Integer value) {
            addCriterion("single_weight <=", value, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightIn(List<Integer> values) {
            addCriterion("single_weight in", values, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightNotIn(List<Integer> values) {
            addCriterion("single_weight not in", values, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightBetween(Integer value1, Integer value2) {
            addCriterion("single_weight between", value1, value2, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andSingleWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("single_weight not between", value1, value2, "singleWeight");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIsNull() {
            addCriterion("demand_number is null");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIsNotNull() {
            addCriterion("demand_number is not null");
            return (Criteria) this;
        }

        public Criteria andDemandNumberEqualTo(Integer value) {
            addCriterion("demand_number =", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotEqualTo(Integer value) {
            addCriterion("demand_number <>", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberGreaterThan(Integer value) {
            addCriterion("demand_number >", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("demand_number >=", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberLessThan(Integer value) {
            addCriterion("demand_number <", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberLessThanOrEqualTo(Integer value) {
            addCriterion("demand_number <=", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIn(List<Integer> values) {
            addCriterion("demand_number in", values, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotIn(List<Integer> values) {
            addCriterion("demand_number not in", values, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberBetween(Integer value1, Integer value2) {
            addCriterion("demand_number between", value1, value2, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("demand_number not between", value1, value2, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNull() {
            addCriterion("total_cost is null");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNotNull() {
            addCriterion("total_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCostEqualTo(Long value) {
            addCriterion("total_cost =", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotEqualTo(Long value) {
            addCriterion("total_cost <>", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThan(Long value) {
            addCriterion("total_cost >", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThanOrEqualTo(Long value) {
            addCriterion("total_cost >=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThan(Long value) {
            addCriterion("total_cost <", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThanOrEqualTo(Long value) {
            addCriterion("total_cost <=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostIn(List<Long> values) {
            addCriterion("total_cost in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotIn(List<Long> values) {
            addCriterion("total_cost not in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostBetween(Long value1, Long value2) {
            addCriterion("total_cost between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotBetween(Long value1, Long value2) {
            addCriterion("total_cost not between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return (Criteria) this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlIn(List<String> values) {
            addCriterion("img_url in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotIn(List<String> values) {
            addCriterion("img_url not in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_product
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 17 14:12:00 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cb_product
     *
     * @mbggenerated Thu Dec 17 14:12:00 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}