package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.CategoryClassProduct;
import com.ssic.cookbook.manager.pojo.CategoryClassProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryClassProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(CategoryClassProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(CategoryClassProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(CategoryClassProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(CategoryClassProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<CategoryClassProduct> selectByExample(CategoryClassProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    CategoryClassProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") CategoryClassProduct record, @Param("example") CategoryClassProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") CategoryClassProduct record, @Param("example") CategoryClassProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(CategoryClassProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class_product
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(CategoryClassProduct record);
}