package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.CategoryClass;
import com.ssic.cookbook.manager.pojo.CategoryClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(CategoryClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(CategoryClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(CategoryClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(CategoryClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<CategoryClass> selectByExample(CategoryClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    CategoryClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") CategoryClass record, @Param("example") CategoryClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") CategoryClass record, @Param("example") CategoryClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(CategoryClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_category_class
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(CategoryClass record);
}