package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.FixingsResultType;
import com.ssic.cookbook.manager.pojo.FixingsResultTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixingsResultTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int countByExample(FixingsResultTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int deleteByExample(FixingsResultTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int insert(FixingsResultType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int insertSelective(FixingsResultType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    List<FixingsResultType> selectByExample(FixingsResultTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    FixingsResultType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") FixingsResultType record, @Param("example") FixingsResultTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByExample(@Param("record") FixingsResultType record, @Param("example") FixingsResultTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByPrimaryKeySelective(FixingsResultType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_result_type
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByPrimaryKey(FixingsResultType record);
}