package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.FixingsMaster;
import com.ssic.cookbook.manager.pojo.FixingsMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixingsMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int countByExample(FixingsMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int deleteByExample(FixingsMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int insert(FixingsMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int insertSelective(FixingsMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    List<FixingsMaster> selectByExample(FixingsMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    FixingsMaster selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") FixingsMaster record, @Param("example") FixingsMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int updateByExample(@Param("record") FixingsMaster record, @Param("example") FixingsMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int updateByPrimaryKeySelective(FixingsMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_fixings_master
     *
     * @mbggenerated Thu Dec 17 16:30:53 CST 2015
     */
    int updateByPrimaryKey(FixingsMaster record);
}