package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.IndependentFixings;
import com.ssic.cookbook.manager.pojo.IndependentFixingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndependentFixingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int countByExample(IndependentFixingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int deleteByExample(IndependentFixingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int insert(IndependentFixings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int insertSelective(IndependentFixings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    List<IndependentFixings> selectByExample(IndependentFixingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    IndependentFixings selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") IndependentFixings record, @Param("example") IndependentFixingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int updateByExample(@Param("record") IndependentFixings record, @Param("example") IndependentFixingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int updateByPrimaryKeySelective(IndependentFixings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_independent_fixings
     *
     * @mbggenerated Tue Jan 05 17:14:24 CST 2016
     */
    int updateByPrimaryKey(IndependentFixings record);
}