package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.IntelligentFixingsStyle;
import com.ssic.cookbook.manager.pojo.IntelligentFixingsStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntelligentFixingsStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int countByExample(IntelligentFixingsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int deleteByExample(IntelligentFixingsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int insert(IntelligentFixingsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int insertSelective(IntelligentFixingsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    List<IntelligentFixingsStyle> selectByExample(IntelligentFixingsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    IntelligentFixingsStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") IntelligentFixingsStyle record, @Param("example") IntelligentFixingsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByExample(@Param("record") IntelligentFixingsStyle record, @Param("example") IntelligentFixingsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByPrimaryKeySelective(IntelligentFixingsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_style
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByPrimaryKey(IntelligentFixingsStyle record);
}