package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.IntelligentFixingsTaste;
import com.ssic.cookbook.manager.pojo.IntelligentFixingsTasteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntelligentFixingsTasteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int countByExample(IntelligentFixingsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int deleteByExample(IntelligentFixingsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int insert(IntelligentFixingsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int insertSelective(IntelligentFixingsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    List<IntelligentFixingsTaste> selectByExample(IntelligentFixingsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    IntelligentFixingsTaste selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") IntelligentFixingsTaste record, @Param("example") IntelligentFixingsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByExample(@Param("record") IntelligentFixingsTaste record, @Param("example") IntelligentFixingsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByPrimaryKeySelective(IntelligentFixingsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_intelligent_fixings_taste
     *
     * @mbggenerated Wed Jan 06 17:02:53 CST 2016
     */
    int updateByPrimaryKey(IntelligentFixingsTaste record);
}