package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.MaterialBigCategory;
import com.ssic.cookbook.manager.pojo.MaterialBigCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialBigCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int countByExample(MaterialBigCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int deleteByExample(MaterialBigCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int insert(MaterialBigCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int insertSelective(MaterialBigCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    List<MaterialBigCategory> selectByExample(MaterialBigCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    MaterialBigCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") MaterialBigCategory record, @Param("example") MaterialBigCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int updateByExample(@Param("record") MaterialBigCategory record, @Param("example") MaterialBigCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int updateByPrimaryKeySelective(MaterialBigCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material_big_category
     *
     * @mbggenerated Mon Dec 21 14:36:30 CST 2015
     */
    int updateByPrimaryKey(MaterialBigCategory record);
}