package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.Material;
import com.ssic.cookbook.manager.pojo.MaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<Material> selectByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    Material selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_material
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(Material record);
}