package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ParamConfig;
import com.ssic.cookbook.manager.pojo.ParamConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int countByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int deleteByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int insert(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int insertSelective(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    List<ParamConfig> selectByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    ParamConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ParamConfig record, @Param("example") ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int updateByExample(@Param("record") ParamConfig record, @Param("example") ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int updateByPrimaryKeySelective(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_param_config
     *
     * @mbggenerated Tue Dec 22 13:25:53 CST 2015
     */
    int updateByPrimaryKey(ParamConfig record);
}