package com.ssic.cookbook.manager.mapper;


import com.ssic.cookbook.manager.pojo.ProductionMethod;
import com.ssic.cookbook.manager.pojo.ProductionMethodExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ProductionMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(ProductionMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(ProductionMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(ProductionMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(ProductionMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<ProductionMethod> selectByExample(ProductionMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    ProductionMethod selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductionMethod record, @Param("example") ProductionMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") ProductionMethod record, @Param("example") ProductionMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(ProductionMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_production_method
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(ProductionMethod record);

   


 

    
}