package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ProductStyle;
import com.ssic.cookbook.manager.pojo.ProductStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(ProductStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(ProductStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(ProductStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(ProductStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<ProductStyle> selectByExample(ProductStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    ProductStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductStyle record, @Param("example") ProductStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") ProductStyle record, @Param("example") ProductStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(ProductStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_style
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(ProductStyle record);
}