package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ProductShape;
import com.ssic.cookbook.manager.pojo.ProductShapeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductShapeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(ProductShapeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(ProductShapeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(ProductShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(ProductShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<ProductShape> selectByExample(ProductShapeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    ProductShape selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductShape record, @Param("example") ProductShapeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") ProductShape record, @Param("example") ProductShapeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(ProductShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_shape
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(ProductShape record);
}