package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ProductMaterial;
import com.ssic.cookbook.manager.pojo.ProductMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int countByExample(ProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int deleteByExample(ProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int insert(ProductMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int insertSelective(ProductMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    List<ProductMaterial> selectByExample(ProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    ProductMaterial selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductMaterial record, @Param("example") ProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByExample(@Param("record") ProductMaterial record, @Param("example") ProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByPrimaryKeySelective(ProductMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_material
     *
     * @mbggenerated Mon Jan 04 14:25:06 CST 2016
     */
    int updateByPrimaryKey(ProductMaterial record);
}