package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ProductColor;
import com.ssic.cookbook.manager.pojo.ProductColorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(ProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(ProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(ProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(ProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<ProductColor> selectByExample(ProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    ProductColor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductColor record, @Param("example") ProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") ProductColor record, @Param("example") ProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(ProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_color
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(ProductColor record);
}