package com.ssic.cookbook.manager.mapper;

import com.ssic.cookbook.manager.pojo.ProductCuisine;
import com.ssic.cookbook.manager.pojo.ProductCuisineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCuisineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int countByExample(ProductCuisineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByExample(ProductCuisineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insert(ProductCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int insertSelective(ProductCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    List<ProductCuisine> selectByExample(ProductCuisineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    ProductCuisine selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductCuisine record, @Param("example") ProductCuisineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByExample(@Param("record") ProductCuisine record, @Param("example") ProductCuisineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKeySelective(ProductCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cb_product_cuisine
     *
     * @mbggenerated Tue Dec 15 14:37:30 CST 2015
     */
    int updateByPrimaryKey(ProductCuisine record);
}